// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'cmcc_auth_theme_config.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CMCCAuthThemeConfig _$CMCCAuthThemeConfigFromJson(Map<String, dynamic> json) {
  return CMCCAuthThemeConfig(
      navColor: json['navColor'] as int,
      navText: json['navText'] as String,
      navTextColor: json['navTextColor'] as int,
      navReturnImgPath: json['navReturnImgPath'] as String,
      authNavTransparent: json['authNavTransparent'] as bool,
      authBGImgPath: json['authBGImgPath'] as String,
      logoImgPath: json['logoImgPath'] as String,
      logoWidth: json['logoWidth'] as int,
      logoHeight: json['logoHeight'] as int,
      logoOffsetY: json['logoOffsetY'] as int,
      logoOffsetY_B: json['logoOffsetY_B'] as int,
      logoHidden: json['logoHidden'] as bool,
      numberColor: json['numberColor'] as int,
      numberSize: json['numberSize'] as int,
      numFieldOffsetY: json['numFieldOffsetY'] as int,
      numFieldOffsetY_B: json['numFieldOffsetY_B'] as int,
      logBtnText: json['logBtnText'] as String,
      logBtnTextColor: json['logBtnTextColor'] as int,
      logBtnImgPath: json['logBtnImgPath'] as String,
      logBtnOffsetY: json['logBtnOffsetY'] as int,
      logBtnOffsetY_B: json['logBtnOffsetY_B'] as int,
      switchAccHidden: json['switchAccHidden'] as bool,
      switchAccTextColor: json['switchAccTextColor'] as int,
      switchOffsetY: json['switchOffsetY'] as int,
      switchOffsetY_B: json['switchOffsetY_B'] as int,
      privacyState: json['privacyState'] as bool,
      clauseOneName: json['clauseOneName'] as String,
      clauseOneUrl: json['clauseOneUrl'] as String,
      clauseTwoName: json['clauseTwoName'] as String,
      clauseTwoUrl: json['clauseTwoUrl'] as String,
      clauseColorBase: json['clauseColorBase'] as int,
      clauseColorAgree: json['clauseColorAgree'] as int,
      uncheckedImgPath: json['uncheckedImgPath'] as String,
      checkedImgPath: json['checkedImgPath'] as String,
      privacyOffsetY: json['privacyOffsetY'] as int,
      privacyOffsetY_B: json['privacyOffsetY_B'] as int,
      sloganTextColor: json['sloganTextColor'] as int,
      sloganOffsetY: json['sloganOffsetY'] as int,
      sloganOffsetY_B: json['sloganOffsetY_B'] as int,
      smsNavTransparent: json['smsNavTransparent'] as bool,
      smsNavText: json['smsNavText'] as String,
      smsLogBtnText: json['smsLogBtnText'] as String,
      smsLogBtnTextColor: json['smsLogBtnTextColor'] as int,
      smsLogBtnImgPath: json['smsLogBtnImgPath'] as String,
      smsBGImgPath: json['smsBGImgPath'] as String,
      smsCodeImgPath: json['smsCodeImgPath'] as String,
      smsCodeBtnTextColor: json['smsCodeBtnTextColor'] as int,
      smsSloganTextColor: json['smsSloganTextColor'] as int,
      customTitleBtnText: json['customTitleBtnText'] as String,
      customTitleBtnTextColor: json['customTitleBtnTextColor'] as int,
      customTitleBtnTextSize: json['customTitleBtnTextSize'] as int,
      customTitleBtnHidden: json['customTitleBtnHidden'] as bool,
      customBodyBtnText: json['customBodyBtnText'] as String,
      customBodyBtnTextColor: json['customBodyBtnTextColor'] as int,
      customBodyBtnTextSize: json['customBodyBtnTextSize'] as int,
      customBodyBtnHidden: json['customBodyBtnHidden'] as bool,
      customBodyBtnOffsetY: json['customBodyBtnOffsetY'] as int,
      cmccDebug: json['cmccDebug'] as bool,
      useCmccSms: json['useCmccSms'] as bool);
}

Map<String, dynamic> _$CMCCAuthThemeConfigToJson(
        CMCCAuthThemeConfig instance) =>
    <String, dynamic>{
      'navColor': instance.navColor,
      'navText': instance.navText,
      'navTextColor': instance.navTextColor,
      'navReturnImgPath': instance.navReturnImgPath,
      'authNavTransparent': instance.authNavTransparent,
      'authBGImgPath': instance.authBGImgPath,
      'logoImgPath': instance.logoImgPath,
      'logoWidth': instance.logoWidth,
      'logoHeight': instance.logoHeight,
      'logoOffsetY': instance.logoOffsetY,
      'logoOffsetY_B': instance.logoOffsetY_B,
      'logoHidden': instance.logoHidden,
      'numberColor': instance.numberColor,
      'numberSize': instance.numberSize,
      'numFieldOffsetY': instance.numFieldOffsetY,
      'numFieldOffsetY_B': instance.numFieldOffsetY_B,
      'logBtnText': instance.logBtnText,
      'logBtnTextColor': instance.logBtnTextColor,
      'logBtnImgPath': instance.logBtnImgPath,
      'logBtnOffsetY': instance.logBtnOffsetY,
      'logBtnOffsetY_B': instance.logBtnOffsetY_B,
      'switchAccHidden': instance.switchAccHidden,
      'switchAccTextColor': instance.switchAccTextColor,
      'switchOffsetY': instance.switchOffsetY,
      'switchOffsetY_B': instance.switchOffsetY_B,
      'clauseOneName': instance.clauseOneName,
      'clauseOneUrl': instance.clauseOneUrl,
      'clauseTwoName': instance.clauseTwoName,
      'clauseTwoUrl': instance.clauseTwoUrl,
      'clauseColorBase': instance.clauseColorBase,
      'clauseColorAgree': instance.clauseColorAgree,
      'uncheckedImgPath': instance.uncheckedImgPath,
      'checkedImgPath': instance.checkedImgPath,
      'privacyOffsetY': instance.privacyOffsetY,
      'privacyOffsetY_B': instance.privacyOffsetY_B,
      'privacyState': instance.privacyState,
      'sloganTextColor': instance.sloganTextColor,
      'sloganOffsetY': instance.sloganOffsetY,
      'sloganOffsetY_B': instance.sloganOffsetY_B,
      'smsNavTransparent': instance.smsNavTransparent,
      'smsNavText': instance.smsNavText,
      'smsLogBtnText': instance.smsLogBtnText,
      'smsLogBtnTextColor': instance.smsLogBtnTextColor,
      'smsLogBtnImgPath': instance.smsLogBtnImgPath,
      'smsBGImgPath': instance.smsBGImgPath,
      'smsCodeImgPath': instance.smsCodeImgPath,
      'smsCodeBtnTextColor': instance.smsCodeBtnTextColor,
      'smsSloganTextColor': instance.smsSloganTextColor,
      'customTitleBtnText': instance.customTitleBtnText,
      'customTitleBtnTextColor': instance.customTitleBtnTextColor,
      'customTitleBtnTextSize': instance.customTitleBtnTextSize,
      'customTitleBtnHidden': instance.customTitleBtnHidden,
      'customBodyBtnText': instance.customBodyBtnText,
      'customBodyBtnTextColor': instance.customBodyBtnTextColor,
      'customBodyBtnTextSize': instance.customBodyBtnTextSize,
      'customBodyBtnHidden': instance.customBodyBtnHidden,
      'customBodyBtnOffsetY': instance.customBodyBtnOffsetY,
      'cmccDebug': instance.cmccDebug,
      'useCmccSms': instance.useCmccSms
    };
