// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'cmcc_auth_theme_config.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CMCCAuthThemeConfig _$CMCCAuthThemeConfigFromJson(Map<String, dynamic> json) {
  return CMCCAuthThemeConfig(
      navColor: json['navColor'] as int,
      navText: json['navText'] as String,
      navTextColor: json['navTextColor'] as int,
      navReturnImgPath: json['navReturnImgPath'] as String,
      logoImgPath: json['logoImgPath'] as String,
      logoWidth: json['logoWidth'] as int,
      logoHeight: json['logoHeight'] as int,
      logoOffsetY: json['logoOffsetY'] as int,
      logoHidden: json['logoHidden'] as bool,
      numberColor: json['numberColor'] as int,
      switchAccHidden: json['switchAccHidden'] as bool,
      switchAccTextColor: json['switchAccTextColor'] as int,
      switchAccOffsetY: json['switchAccOffsetY'] as int,
      numFieldOffsetY: json['numFieldOffsetY'] as int,
      logBtnText: json['logBtnText'] as String,
      logBtnOffsetY: json['logBtnOffsetY'] as int,
      logBtnTextColor: json['logBtnTextColor'] as int,
      logBtnBackgroundPath: json['logBtnBackgroundPath'] as String,
      uncheckedImgPath: json['uncheckedImgPath'] as String,
      checkedImgPath: json['checkedImgPath'] as String,
      privacyOffsetY: json['privacyOffsetY'] as int,
      clauseName: json['clauseName'] as String,
      clauseUrl: json['clauseUrl'] as String,
      clauseBaseColor: json['clauseBaseColor'] as int,
      clauseColor: json['clauseColor'] as int,
      clauseNameTwo: json['clauseNameTwo'] as String,
      clauseUrlTwo: json['clauseUrlTwo'] as String,
      sloganOffsetY: json['sloganOffsetY'] as int,
      sloganTextColor: json['sloganTextColor'] as int,
      smsNavText: json['smsNavText'] as String,
      smsLogBtnText: json['smsLogBtnText'] as String,
      smsLogBtnTextColor: json['smsLogBtnTextColor'] as int,
      smsLogBtnImgPath: json['smsLogBtnImgPath'] as String,
      customTitleBtnText: json['customTitleBtnText'] as String,
      customTitleBtnTextColor: json['customTitleBtnTextColor'] as int,
      customTitleBtnTextSize: json['customTitleBtnTextSize'] as int,
      customTitleBtnHidden: json['customTitleBtnHidden'] as bool,
      customBodyBtnText: json['customBodyBtnText'] as String,
      customBodyBtnTextColor: json['customBodyBtnTextColor'] as int,
      customBodyBtnTextSize: json['customBodyBtnTextSize'] as int,
      customBodyBtnHidden: json['customBodyBtnHidden'] as bool,
      customBodyBtnOffsetY: json['customBodyBtnOffsetY'] as int,
      cmccDebug: json['cmccDebug'] as bool,
      useCmccSms: json['useCmccSms'] as bool);
}

Map<String, dynamic> _$CMCCAuthThemeConfigToJson(
        CMCCAuthThemeConfig instance) =>
    <String, dynamic>{
      'navColor': instance.navColor,
      'navText': instance.navText,
      'navTextColor': instance.navTextColor,
      'navReturnImgPath': instance.navReturnImgPath,
      'logoImgPath': instance.logoImgPath,
      'logoWidth': instance.logoWidth,
      'logoHeight': instance.logoHeight,
      'logoOffsetY': instance.logoOffsetY,
      'logoHidden': instance.logoHidden,
      'numberColor': instance.numberColor,
      'switchAccHidden': instance.switchAccHidden,
      'switchAccTextColor': instance.switchAccTextColor,
      'switchAccOffsetY': instance.switchAccOffsetY,
      'numFieldOffsetY': instance.numFieldOffsetY,
      'logBtnText': instance.logBtnText,
      'logBtnOffsetY': instance.logBtnOffsetY,
      'logBtnTextColor': instance.logBtnTextColor,
      'logBtnBackgroundPath': instance.logBtnBackgroundPath,
      'uncheckedImgPath': instance.uncheckedImgPath,
      'checkedImgPath': instance.checkedImgPath,
      'privacyOffsetY': instance.privacyOffsetY,
      'clauseName': instance.clauseName,
      'clauseUrl': instance.clauseUrl,
      'clauseBaseColor': instance.clauseBaseColor,
      'clauseColor': instance.clauseColor,
      'clauseNameTwo': instance.clauseNameTwo,
      'clauseUrlTwo': instance.clauseUrlTwo,
      'sloganOffsetY': instance.sloganOffsetY,
      'sloganTextColor': instance.sloganTextColor,
      'smsNavText': instance.smsNavText,
      'smsLogBtnText': instance.smsLogBtnText,
      'smsLogBtnTextColor': instance.smsLogBtnTextColor,
      'smsLogBtnImgPath': instance.smsLogBtnImgPath,
      'customTitleBtnText': instance.customTitleBtnText,
      'customTitleBtnTextColor': instance.customTitleBtnTextColor,
      'customTitleBtnTextSize': instance.customTitleBtnTextSize,
      'customTitleBtnHidden': instance.customTitleBtnHidden,
      'customBodyBtnText': instance.customBodyBtnText,
      'customBodyBtnTextColor': instance.customBodyBtnTextColor,
      'customBodyBtnTextSize': instance.customBodyBtnTextSize,
      'customBodyBtnHidden': instance.customBodyBtnHidden,
      'customBodyBtnOffsetY': instance.customBodyBtnOffsetY,
      'cmccDebug': instance.cmccDebug,
      'useCmccSms': instance.useCmccSms
    };
